---
name: Echo Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  echo-job:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_VAR: "available-to-all-steps"
    steps:
      - name: Use Job-Level Variable
        run: echo "$JOB_LEVEL_VAR"
      - name: Echo Message
        run: echo "Hello, DevOps!"
      - name: Multi line step
        run: |
          pwd
      - name: Display GitHub Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
      - name: Use Secrets and Variables
        run: |
          echo "Variable: ${{ vars.MY_VARIABLE }}"
          echo "Secret: ${{ secrets.MY_SECRET }}"
      - name: Display Runner Environment Variables
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Name: ${{ runner.name }}"
          echo "Runner Tool Cache: ${{ runner.tool_cache }}"
          echo "Runner Temp: ${{ runner.temp }}"
          echo "Runner Workspace: ${{ runner.workspace }}"
      - name: Built in System Environment Variables
        run: |
          echo "HOME: $HOME"
          echo "PATH: $PATH"
          echo "USER: $USER"
          echo "PWD: $PWD"
      - name: Custom Environment Variables
        env:
          CUSTOM_VAR: "custom-value"
          ANOTHER_VAR: "another-value"
        run: |
          echo "Custom: $CUSTOM_VAR"
          echo "Another: $ANOTHER_VAR"
      - name: Set Environment Variable
        run: |
          echo "MY_VALUE=test123" >> $GITHUB_ENV
      
      - name: Use Environment Variable
        run: |
          echo "Value: $MY_VALUE"
